DROP TABLE IF EXISTS Rotations;
DROP TABLE IF EXISTS Options;
DROP TABLE IF EXISTS Tests;
DROP TABLE IF EXISTS TestSessions;

CREATE TABLE TestSessions
(
	Id CHAR(36) PRIMARY KEY,
	ReadableIdentifier VARCHAR(50) NOT NULL
);

CREATE TABLE Tests
(
	Id CHAR(36) PRIMARY KEY,
	SessionId CHAR(36) NOT NULL,
	ReadableIdentifier VARCHAR(50) NOT NULL,
	Type INTEGER NOT NULL,
	Duration DECIMAL NOT NULL,
	UserConfidence INTEGER NOT NULL,
	Metadata TEXT NOT NULL DEFAULT '{}',
	
	CONSTRAINT test_session FOREIGN KEY(SessionId) REFERENCES TestSessions(Id)
);

CREATE TABLE Options
(
	Id CHAR(36) PRIMARY KEY,
	TestId CHAR(36) NOT NULL,
	ReadableIdentifier VARCHAR(50) NOT NULL,
	SelectedState INTEGER NOT NULL,
	CorrectState INTEGER NOT NULL,
	
	CONSTRAINT fk_test_options FOREIGN KEY(TestId) REFERENCES Tests(Id)
);

CREATE TABLE Rotations
(
	Id CHAR(36) PRIMARY KEY,
	TestId CHAR(36) NOT NULL,
	ReadableIdentifier VARCHAR(50) NOT NULL,
	InteractionNumber INTEGER NOT NULL,
	DeltaTime DECIMAL NOT NULL,
	RotationDegrees DECIMAL NOT NULL,
	
	CONSTRAINT fk_test_rotations FOREIGN KEY(TestId) REFERENCES Tests(Id)
);